name: Node CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install blade-formatter
        run: npm install --save-dev blade-formatter
      - name: run blade-formatter
        run: ./node_modules/.bin/blade-formatter __tests__/**/*.blade.php
